---
name: CI

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    permissions:
      contents: read
      packages: read
      pull-requests: write
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-quality.yml@375d104f6ca707f4f35344170a42bf901a617a9f # v0.15.0
    with:
      tooling-ref: "375d104f6ca707f4f35344170a42bf901a617a9f"
